### ISSUE TITLE
Sensor set up

### ISSUE THREAD

**Issue by enting8696** [valeoai/MVRSS#2]
Hi, in the paper section 2.1 Automotive radar sensing,  you say that - 

**With conventional FMCW radars the RAD tensor is usually not available as it is too computing intensive to estimate.** 

so what is difference between conventional FMCW and others FMCW  radar?

In addition, what CARRADA dataset camera and radar sensor setup? and the network cost time (ms) is possible to on-road online?

Thanks you, hope you can give me some advice.

**Comment by ArthurOuaknine** [comment]
Hello.

We consider the conventional FMCW radars as sensors with low number of pairs of virtual antennas (8 in our case) inducing a low angular resolution.
The high definition (HD) radar is more common now, hundreds of virtual antennas.
Here is a reference of our new dataset using a HD radar with 192 pairs of virtual antennas: https://arxiv.org/abs/2112.10646

The specs of the camera and radar, data and sensors, used in CARRADA are detailed in our article here: https://arxiv.org/abs/2005.01456

We do not provide the inference time of our proposed architecture for the simple reason that it depends on the hardware you use (one CPU, multiple CPU, one GPU, multiple GPU, which ones and so on). We let the users evaluate this metric by themself. We provide the size of the models which is an indicator of the number of parameters used.

I hope it will help.
