### ISSUE TITLE
How did you generate the AD map?

### ISSUE THREAD

**Issue by yaoshanliang** [valeoai/MVRSS#4]
Wonderful work.

I can get the RD and RA map from `https://github.com/valeoai/carrada_dataset`, can you help me on generating the AD map?

**Comment by ArthurOuaknine** [comment]
Hi.
The CARRADA dataset can be downloaded here: http://download.tsi.telecom-paristech.fr/Carrada/
The "Carrada.tar.gz" file should include the AD view as well as the two others.
If you want to generate the AD, you can download the "Carrada_RAD.tar.gz" file containing the entire RAD tensors and aggregate them using equation 1 (with the proper axis) from our paper here: https://arxiv.org/pdf/2103.16214.pdf
Best.
