### ISSUE TITLE
test result 

### ISSUE THREAD

**Issue by nlm676** [valeoai/MVRSS#5]
Is the pre-training weight public
The miou I reproduce can't reach the data in the paper
I look forward to your reply, thank you

**Comment by ArthurOuaknine** [comment]
Hello.
The pre-trained models are available in the release v0.1 here: [https://github.com/valeoai/MVRSS/releases/tag/v0.1](https://github.com/valeoai/MVRSS/releases/tag/v0.1)
You should be able to use them by following the corresponding instructions in the README.
Hope it will help.
