### ISSUE TITLE
Rotate RD Range vect to match zero range

### ISSUE THREAD

**Issue by LSu666** [valeoai/MVRSS#6]
Why do you need to swap the second and third dimensions?
~~~ python
rd_range_probs = torch.max(rd_softmax, dim=3, keepdim=True)[0]
rd_range_probs = torch.rot90(rd_range_probs, 2, [2, 3])
ra_range_probs = torch.max(ra_softmax, dim=3, keepdim=True)[0]
~~~

**Comment by ArthurOuaknine** [comment]
The axes are not swapped, it indicates on which axis the rotation should be applied.
See pytorch doc: https://pytorch.org/docs/stable/generated/torch.rot90.html
Note that the RD is rotate so the min and max range values are matched with the RA.
